#!/bin/bash
#Basic personal firewall for Netfilter
#Chris Wood - A00741285 - chriswood.ca@gmail.com
################################################
#Drops all connections by default
#Permits inbound/outbound ssh
#Permits inbound/outbound www
#Drops inbound traffic to port 80 from sport < 1024
#Drops all incoming packets from port 0 and incoming traffic to port 0
#IP accounting rules set by user defined chains to monitor network traffic

#user-configurable
ALLOWED_PORTS=22,80
BLOCKED_PORTS=0-1024

#implementation__DO NOT TOUCH BELOW

#clear out any previous chain rules and chains
iptables -F
iptables --flush
iptables -X

#create user defined chains for IP accouting of www, ssh, and other traffic
#these chains should have their traffic accepted
iptables -N ssh-in
iptables -N ssh-out
iptables -A ssh-in -j ACCEPT
iptables -A ssh-out -j ACCEPT

iptables -N www-in
iptables -N www-out
iptables -A www-in -j ACCEPT
iptables -A www-out -j ACCEPT

iptables -N other-in
iptables -N other-out
iptables -A other-in -j ACCEPT
iptables -A other-out -j ACCEPT

#Permit inbound and output traffic for allowed ports
#allow SSH
iptables -A INPUT -p tcp -d localhost --dport 22 -j ssh-in
iptables -A OUTPUT -p tcp -s localhost -d 0/0 --dport 22 -j ssh-out
iptables -A INPUT -p tcp -d localhost --dport 22 -j ACCEPT
iptables -A OUTPUT -p tcp -s localhost -d 0/0 --dport 22 -j ACCEPT

#allow www
iptables -A INPUT -p tcp -d localhost --dport 80 -j www-in
iptables -A OUTPUT -p tcp -s localhost -d 0/0 --dport 80 -j www-out
iptables -A INPUT -p tcp -d localhost --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -s localhost -d 0/0 --dport 80 -j ACCEPT

#allow DNS traffic
iptables -A OUTPUT -p udp --dport 53 -s localhost -j other-out
iptables -A INPUT -p udp --dport 53 -d localhost -j other-in
iptables -A OUTPUT -p udp --dport 53 -s localhost -j ACCEPT 
iptables -A INPUT -p udp --dport 53 -d localhost -j ACCEPT

#allow DHCP traffic
iptables -A OUTPUT -p udp --dport 67:68 -s localhost -j other-out
iptables -A INPUT -p udp --sport 67:68 -d localhost -j other-in
iptables -A OUTPUT -p udp --dport 67:68 -s localhost -j other-out
iptables -A INPUT -p udp --sport 67:68 -d localhost -j other-in

iptables -A INPUT -p tcp --dport 80 --sport 0:1023 -j DROP

iptables -A INPUT -p tcp --dport 0 -d localhost -j DROP


#set default polcies on the firewall to drop all incoming, outgoing and forwarding traffic
iptables -A INPUT -j DROP
iptables -A FORWARD -j DROP
iptables -A OUTPUT -j DROP

iptables -L -v
