#!/bin/bash
#Flushes all iptables rules and chains
#Changes default chain policies back to ACCEPT
iptables -F
iptables --flush
iptables -X
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT

iptables -L
